/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function doInitialize(reportNetworkStatus: ((err: Error | null, arg: NetworkStatus) => any), reportWlanStatus: ((err: Error | null, arg: WlanStatus) => any), thresholdDrop: number, thresholdRecover: number, reportNetQuality: ((err: Error | null, arg: NetworkQualitySample) => any), log: ((err: Error | null, arg: string) => any)): void

export interface NetworkQualitySample {
  latencyAvgMs: number
  latencyMinMs: number
  latencyMaxMs: number
  jitterMs: number
  packetLossPercent: number
  tcpRetransmissionPercent: number
  tcpSegmentsSent: number
  tcpSegmentsRetransmitted: number
}

export interface NetworkStatus {
  status: number
}

export interface WlanStatus {
  strong: number
  quality: number
  rssi: number
}
